AKCORE-254: RPC batching and event based poll. (#4)
confluentinc/kafka pull request #1422
Opened 2024-08-05 10:33 UTC by smjn

### What
- Build infra code to allow for RPC batching in PersisterStateManager.
- Change poll mechanism to be triggered on various events (new RPC, completion of RPC on specific parition key etc.)

### Why
- Batching improves performance by leveraging the turnaround time of an RPC on a specific node n1 (share coord leader) to batch multiple RPCs into a single one for subsequent requests. For example: 
  - Suppose we get a Write RPC r1 for n1.
  - We send this RPC in standard way.
  - While r1 is inflight, lets say 3 more RPCs for n1 are received (r2, r3, r4)
  - coalesce and batch r2, r3, and r4 into a single RPC R1.
  - When r1 completes, make a single RPC R1 to n1
  - This saves 2 network calls.
  - The result of R1 is broken down to create response objects for individual RPCs (r2, r3, r4)
- Event based poll is more performant and simpler to implement.

### Testing
-  Added and updated tests at requisite places.

2024-08-05 21:09 UTC, AndrewJSchofield requested changes
Thanks for the PR. A few comments to address.

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +        nodeRPCMap.get(node).get(handler.rpcType()).get(handler.groupId).add(handler);
This method can be simplified I think. There's no need to do the repeated get() calls, and you could chain the computeIfAbsent() calls instead.

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +        sender.wakeup();
Does the wakeup really need to be inside the synchronized block?

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +              .setTopics(partitionData.entrySet().stream().map(
nit: nicer to break the line between `.stream()` and `map(` I think.

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +              .setTopics(partitionData.entrySet().stream().map(
ditto

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
>      private int findCoordattempts = 0;
Typo: Should be `findCoordBackoff` and `findCoordAttempts`.

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
>    public abstract class PersisterStateManagerHandler implements RequestCompletionHandler {
It would be nice to have a comment for this abstract class describing what it's for. There's a subclass for each of the RPC types that can be batched, if I'm reading it right.

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +  private final Map<RPCType, Set<Node>> inFlight = new HashMap<>();
I'd like to see // comments for these 4 members which indicate what they're for.

2024-08-05 21:09 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +      if (generateCallback != null) {
The comment above this line really doesn't do it justice :) Can we have a better comment please?

2024-08-06 09:01 UTC, smjn commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +        nodeRPCMap.get(node).get(handler.rpcType()).get(handler.groupId).add(handler);
Did it this way for readability

2024-08-06 13:10 UTC, AndrewJSchofield commented on server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
> +      // 1. A queue which will contain FIND_CORD RPCs and other non-batchable RPCs.
FIND_COORDINATOR

2024-08-06 13:12 UTC, AndrewJSchofield approved these changes

2024-08-06 14:39 UTC, merged